auth:
  build: ./microservices/auth
  links:
    - db
    - session
  env_file:
    - ./app.env
user:
  build: ./microservices/user
  links:
    - db
    - session
  env_file:
    - ./app.env
db:
  image: postgres
  env_file:
    - ./db.env
session:
  image: redis
proxy:
  image: nginx
  ports:
    - 3000:80
  volumes:
    - ./proxy/static:/usr/share/nginx/html:ro
    - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
  links:
    - auth:auth
    - user:user
